apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliyoutubedownloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliyoutubedownloader
  template:
    metadata:
      labels:
        app: cliyoutubedownloader
    spec:
      containers:
        - name: cliyoutubedownloader
          image: nikosk598/youtubedownloader:latest
          stdin: true
          tty: true
          env:
            - name: REDIS_HOST
              value: redis
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cliyoutubedownloaderservice
spec:
  selector:
    app: cliyoutubedownloader
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
